# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Matt's Game Dev Notebook
email: matt@unrealist.org
description: >- # this means to ignore newlines until "baseurl:"
   Matt's Game Dev Notebook is a blog dedicated to sharing the knowledge and experience of an Unreal Engine enthusiast.
twitter_username: unrealist_matt
github_username: the-unrealist
minimal_mistakes_skin: dark
search: true
repository: the-unrealist/the-unrealist

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-spaceship
  
jekyll-spaceship:
  mermaid-processor:
    config:
      theme: dark

author:
  name   : "Matt"
  avatar : "/assets/images/orange.png"
  bio    : "Unreal Engine Enthusiast"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/unrealist_matt"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/the-unrealist"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/unrealist_matt"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/the-unrealist"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true
      show_date: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
  
comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOIFvutA" # Shown during giscus setup at https://giscus.app
    category_name        : "Announcements" # Full text name of the category
    category_id          : "DIC_kwDOIFvutM4CRsVd" # Shown during giscus setup at https://giscus.app
    discussion_term      : "og:title" # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : "1" # '1' for enabled (default), '0' for disabled
    theme                : "preferred_color_scheme" # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
