theme: minima
title: The Unrealist
description: Description here
permalink: /:slug/
show_excerpts: true
author:
  name: Matt
  email: matt@unrealist.org
  
minima:
  social_links:
    twitter: unrealist_matt
